---
# This automation simulates the use of the IKEA TRADFRI Remote control
# connected through ZHA.

blueprint:
  source_url: https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_styrbar_color.yaml

  name: ZHA - IKEA TRADFRI - STYRBAR - Custom Music

  description: >-
    This automation simulates the use of the IKEA TRADFRI STYRBAR remote control
    connected through ZHA.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: IKEA of Sweden
              model: Remote Control N2

    media_player:
      name: media_player
      description: Select the media entity you wish to control.
      selector:
        entity:
          filter:
            - domain: media_player


mode: restart
max_exceeded: silent

variables:
  var_media_player: !input media_player


trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Short-Press on the dim-up button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "step" }}'
          - condition: state
            entity_id: !input media_player
            state: "{{ states.media_player.media_player.living_room.attributes.volume_level}}"
        sequence:
          - service: media_player.volume_up
            target:
              entity_id: !input media_player
            data:



      # Long-Press on the dim-up button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - service: media_player.volume_up
                  target:
                    entity_id: !input media_player
                  data:
                    volume_step_pct: 5
                    
      # Short-Press on the dim-down button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "step" }}'
        sequence:
          - service: media_player.volume_down
            target:
              entity_id: !input media_player
            data:

      # Long-Press on the dim-down button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - service: media_player.volume_up
                  target:
                    entity_id: !input media_player
                  data:
                    volume_step_pct: -5

      # Short-Press on the left button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "press" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [257,13,0] }}"
        sequence:
          - service: media_player.turn_on
            target:
              entity_id: !input media_player
            data:
              hs_color:
                - '{{ state_attr(var_media_player, "hs_color")[0] }}'
                - >-
                  {% if state_attr(var_media_player, "hs_color")[1] - 20 < 0 %}
                    {{ state_attr(var_media_player, "hs_color")[1] - 20 + 100 }}
                  {% else %}
                    {{ state_attr(var_media_player, "hs_color")[1] - 20 }}
                  {% endif %}

      # Long-Press on the left button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "hold" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [3329,0] }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: media_player.turn_on
                  target:
                    entity_id: !input media_player
                  data:
                    hs_color:
                      - '{{ state_attr(var_media_player, "hs_color")[0] }}'
                      - >-
                        {% if state_attr(var_media_player, "hs_color")[1] - 10 < 0 %}
                          {{ state_attr(var_media_player, "hs_color")[1] - 10 + 100 }}
                        {% else %}
                          {{ state_attr(var_media_player, "hs_color")[1] - 10 }}
                        {% endif %}

      # Short-Press on the right button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "press" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [256,13,0] }}"
        sequence:
          - service: media_player.turn_on
            target:
              entity_id: !input media_player
            data:
              hs_color:
                - >-
                  {% if state_attr(var_media_player, "hs_color")[0] + 18 > 360 %}
                    {{ state_attr(var_media_player, "hs_color")[0] + 18 - 360 }}
                  {% else %}
                    {{ state_attr(var_media_player, "hs_color")[0] + 18 }}
                  {% endif %}
                - '{{ state_attr(var_media_player, "hs_color")[1] }}'

      # Long-Press on the right button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "hold" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [3328,0] }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: media_player.turn_on
                  target:
                    entity_id: !input media_player
                  data:
                    hs_color:
                      - >-
                        {% if state_attr(var_media_player, "hs_color")[0] + 18 > 360 %}
                          {{ state_attr(var_media_player, "hs_color")[0] + 18 - 360 }}
                        {% else %}
                          {{ state_attr(var_media_player, "hs_color")[0] + 18 }}
                        {% endif %}
                      - '{{ state_attr(var_media_player, "hs_color")[1] }}'

    # Any other event will cancel the repeat loops.
    default: []
